### ISSUE TITLE
write_doc only substitutes attributes partially

### ISSUE THREAD

**Issue by verwinv** [jmurty/xml4h#13]
Hello, 

I have two sets of XMLs that describe the same content (articles in an academic journal) with differing schema versions and different content that I was hoping to merge with the help of your xml4h library. I tried starting out by replacing the attributes of the root tag:

`<doi_batch xmlns="http://www.crossref.org/schema/4.3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4.3.0" xsi:schemaLocation="http://www.crossref.org/schema/4.3.0 http://www.crossref.org/schema/deposit/crossref4.3.0.xsd">`

should be replaced with:

`<doi_batch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.crossref.org/schema/4.4.2 https://www.crossref.org/schemas/crossref4.4.2.xsd" xmlns="http://www.crossref.org/schema/4.4.2" xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1" xmlns:fr="http://www.crossref.org/fundref.xsd"    xmlns:ai="http://www.crossref.org/AccessIndicators.xsd" version="4.4.2">`

Somehow, when applying the script below, the attributes all update, *except* the xmlns link, which keeps referring to: "http://www.crossref.org/schema/4.3.0" instead of "http://www.crossref.org/schema/4.4.2".

Could I ask for your help in assessing whether we're approaching this the wrong way or it's part of the way the library functions?

Kind regards, and thanks for the help,
Erwin

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 23 15:41:16 2020
​
@authors: erwin, Philo
"""
​
import xml4h
​
attrsWanted = {
  'xmlns:xsi': "http://www.w3.org/2001/XMLSchema-instance", 
  'xsi:schemaLocation': "http://www.crossref.org/schema/4.4.2 https://www.crossref.org/schemas/crossref4.4.2.xsd", 
  'xmlns': "http://www.crossref.org/schema/4.4.2", 
  'xmlns:jats': "http://www.ncbi.nlm.nih.gov/JATS1", 
  'xmlns:fr': "http://www.crossref.org/fundref.xsd", 
  'xmlns:ai': "http://www.crossref.org/AccessIndicators.xsd", 
  'version': "4.4.2"
}
​
# Parse an XML document
doc = xml4h.parse('crossref-view-issue04_test4.xml')
​
# Find an Element node of interest
doi_batch = doc.doi_batch
​
print("\n🌱  before change:")
for item in doi_batch.attributes.items():
  print(item)
​
print("\n💧  wanted change:")
for item in attrsWanted.items():
  print(item)
​
doi_batch.attributes = attrsWanted
print("\n🌳  after change:")
for item in doi_batch.attributes.items():
  print(item)
​
​
# Write to a file
with open('crossref-view-issue04_test4-updated.xml', 'wb') as f:
    doi_batch.write_doc(f)

```

**Comment by jmurty** [comment]
Hi @verwinv you have found a seemingly simple requirement that turns out to be surprisingly difficult. Lucky you!

Working with XML namespaces is particularly difficult in the libraries that `xml4h` wraps, because although namespace definitions mostly *seem* to work like standard element attributes, behind the scenes they can be treated very differently because they contain vital metadata about the element (and its subtree). And it is quite easy to end up with element attributes that say one thing, while the underlying namespaces say a different thing and are more authoritative.

In the best case, you might be able to do what you need by making `xml4h` use a different underlying XML processing library. It uses `lxml` by default if it's available, but `lxml` will not handle your namespace changes well.

### (c)ElementTree adapter

Try forcing `xml4h` to use the (c)ElementTree library when you parse the input document, and see if you can create the output document you want. But always be careful to check the actual output document, not just the apparent attributes.

```python
# Parse an XML document using the cElementTree library adapter
doc = xml4h.parse(
  'crossref-view-issue04_test4.xml',
  adapter=xml4h.cElementTreeAdapter  # or xml4h.ElementTreeAdapter
)

# Set/change namespace attributes
doi_batch.set_attributes(attrsWanted)

# Output document and check namespaces are correct throughout
```

In my testing the (c)ElementTree library seems to do the right thing when you adjust top-level namespace attributes, but I cannot be sure it will do the right thing as you copy or `clone_node()` elements from two source documents into one.

Also be sure to use the `set_attributes()` method to add or change namespace attributes when using (c)ElementTree, since I have just discovered that using `.attributes = blah` can **remove** namespaces entirely from descendant nodes for this particular adapter.


### Minidom adapter

Alternately force `xml4h` to use the minidom library.

```python
# Parse an XML document using the "minidom" library adapter
doc = xml4h.parse(
  'crossref-view-issue04_test4.xml',
  adapter=xml4h.XmlDomImplAdapter)

# Set/change namespace attributes
doi_batch.attributes = attrsWanted

# Output document and check namespaces are correct throughout
```

Again, in my basic testing the minidom library seems to do the right thing when you adjust top-level namespace attributes, but you will need to test your entire process to be sure there are no weird namespacing problems.

A nice thing with the minidom adapter is the `.attributes = blah` assignment doesn't seem to clobber namespaces of descendant nodes.


### lxml adapter

If `xml4h` is using `lxml` as the underlying implementation – which is likely since this is the default and generally the best choice when it's available – you might be in for a whole lot of namespace pain. You can check which underlying library `xml4h` is using by checking the `adapter` attribute on a node:

```
doi_batch.adapter  # => <xml4h.impls.lxml_etree.LXMLAdapter object at ...>
```

In the `lxml` library, element namespaces are **immutable** once defined on an element. I have not yet found a way around this, so `xml4h` cannot apply your namespace changes, nor can you make such changes even if you use the `lxml` objects directly.

See for example what happens if you try to adjust an element's namespaces after it has been created/parsed, when bypassing `xml4h` entirely to use the underlying `lxml` objects directly:

```python
import xml4h, lxml

doc = xml4h.parse(
  'crossref-view-issue04_test4.xml',
  adapter=xml4h.LXMLAdapter)

# Get underlying lxml Element object
lxml_elem = doc.root.impl_node

# Check lxml Element, has old 4.3.0 namespace
lxml_elem  # => <Element {http://www.crossref.org/schema/4.3.0}doi_batch at ...>
# Has 4.3.0 namespace for default ("xmlns") namespace in internal `nsmap`
lxml_elem.nsmap[None]  # => 'http://www.crossref.org/schema/4.3.0'
# Has no "xmlns" attribute
lxml_elem.attrib.get("xmlns")  # => None

# Set "xmlns" (default) namespace to new 4.4.2
lxml_elem.nsmap[None] = 'http://www.crossref.org/schema/4.4.2'
# But doing so has no effect on immutable `nsmap`...
lxml_elem.nsmap[None]  # => 'http://www.crossref.org/schema/4.3.0'
# ...nor on serialised XML output
lxml.etree.tostring(lxml_elem)
b'<doi_batch xmlns="http://www.crossref.org/schema/4.3.0"...'

# Set new "xmlns" as attribute
lxml_elem.attrib["xmlns"] = 'http://www.crossref.org/schema/4.4.2'
# Namespace attribute seems to be set...
lxml_elem.attrib["xmlns"]  # => 'http://www.crossref.org/schema/4.4.2'
# ...but this has no effect on the real namespace in `nsmap`...
lxml_elem.nsmap[None] # => 'http://www.crossref.org/schema/4.3.0'
# ...and XML output now has TWO "xmlns" attributes!
lxml.etree.tostring(lxml_elem)
b'<doi_batch xmlns="http://www.crossref.org/schema/4.3.0" ... xmlns="http://www.crossref.org/schema/4.4.2">...'
```

Given the immutability of defined namespaces in `lxml` I expect you could run into all kinds of problems trying to merge two documents if they use their own namespaces.

### Ugly but possibly sufficient text replacement hack

Depending on how big a problem it ends up being merging XML docs with namespaces, or if you want to keep using the `lxml` library and adapter, you might be able to work around the problem entirely by changing namespaces in the XML text before parsing.

For example, to convert the default "xmlns" namespace from http://www.crossref.org/schema/4.3.0 to http://www.crossref.org/schema/4.4.2:

```python
# Hack to replace xmlns attribute in raw text
xml = open('crossref-view-issue04_test4.xml').read()
xml = xml.replace(
  'xmlns="http://www.crossref.org/schema/4.3.0"',
  'xmlns="http://www.crossref.org/schema/4.4.2"')

doc = xml4h.parse(xml)
```

As awful and hacky as this is, it might be a reasonable approach if you only need to *change* (as opposed to add) just one or a few namespaces. And you might end up having more control, more clearly, with this hack than trying to make unwilling XML libraries do what you want.


I hope some of this helps? I had to review and rediscover a lot of these quirks myself just now, and it reminded me of why I wanted to build `xml4h` in the first place to try and hide some of these warts. But clearly it doesn't (yet?) hide them all.

**Comment by verwinv** [comment]
Dear @jmurty, thank you so much for your extensive explanation and for taking the time to test all the possible solutions. Since my original approach was searching and replacing text, I'll most likely stick with the ugly/sufficient replacement approach for now -- but will dig in to understand the namespaces concept in XML a bit better.
